### ISSUE TITLE
Cart Abandonment

### ISSUE THREAD

**Issue by terryupton** [madebyshape/commerce-widgets#1]
The Cart Abandonment widget seems to show the same value for completed carts and abandoned carts. I believe the abounded is showing the incorrect value and this is in-fact showing the completed number instead.

I assume a completed cart is a completed order? So should this figure show the same as the order totals for that period? As this seems to differ too. In the instance I have. I have a total of 18 orders for the month but the completed cart shows 15 and the abandoned cart shows 15 too.

**Comment by madebyshape** [comment]
Whoops your right, I'll get this fixed this weekend.

It should show the total # of carts abandoned and also the # successful carts (Orders) as a number and on the graph. At the moment it's showing 1 and 2 for me, which isn't correct at all.

I'll update this issue when I've pushed a fix.

**Comment by madebyshape** [comment]
Terry - This should be fixed now in the latest release. I also adjusted the colours on the graph to make it more obvious which is the completed vs abandoned. 

Let me know if this works better for you.

**Comment by terryupton** [comment]
Thanks for this. it's great and it seems to pull the right numbers in now. I will test it over the next few days in case I spot any issues. :-)

**Comment by madebyshape** [comment]
Perfect :D Yeah going to close this issue now, but any other problems with it, just reopen the issue.

Enjoy!
