### ISSUE TITLE
Cart Abandonment Widget Totals

### ISSUE THREAD

**Issue by terryupton** [madebyshape/commerce-widgets#4]
I have noticed that on the Cart Abandonment Widget the total for successful (completed) carts never goes above 100.

**Comment by bymayo** [comment]
Will check this out and see whats going on :)

**Comment by terryupton** [comment]
Thanks. Any luck with this? I also noticed the abandoned also seems to limit out at 100 too.

**Comment by bymayo** [comment]
Sorry for the delay on this, been snowed under. Should be fixed now with some minor improvements. I plan on adding a few more widgets and tweaks over the next few weeks also.

**Comment by terryupton** [comment]
Thanks for fixing this. I can't see an official update via Craft updated panel though? Sorry.
Some more widgets would be great. Let me know if you want me to help with any testing etc. You can get me on the Craft Slack channels.
